import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { logout } from "@/actions/signupAction";
import { Power } from "lucide-react";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function AuthRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex w-full justify-between items-center p-3 bg-yellow-100">
          <p>Wellcome back</p>
          <form action={logout}>
            <button className="py-2 px-4 bg-zinc-700 text-white rounded-md text-sm flex items-center gap-x-1">
              Logout <Power size={18} />
            </button>
          </form>
        </header>
        {children}
      </body>
    </html>
  );
}
